15_Facebook/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

15_Facebook/facebook/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),

    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

15_Facebook/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index , name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/like/', views.like, name='like'),
]

15_Facebook/manytomany/models.py
from django.db import models

# Create your models here.
class Doctor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Patient(models.Model):
    name = models.CharField(max_length=100)
    doctors = models.ManyToManyField(Doctor, related_name='patients')

    def __str__(self):
        return self.name

# class Reservation(models.Model):
#     doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
#     patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
#     time = models.CharField(max_length=100)
#     location = models.CharField(max_length=100, default='3층')

#     def __str__(self):
#         return f"{self.doctor.name}의사 : {self.patient.name}환자"

15_Facebook/posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL , on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

15_Facebook/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','content',)

15_Facebook/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')

    else:
        form = UserCreationForm()
        context = {
            'form':form
        }

        return render(request, 'accounts/form.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

15_Facebook/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm
from .models import Post

# Create your views here.
def index(request):
    posts = Post.objects.all()
    context = {
        'posts':posts
    }
    return render(request, 'posts/index.html', context)

def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')

    else:
        forms = PostForm()
    context = {
        'forms':forms
    }
    return render(request, 'posts/form.html', context)

def like(request, id):
    post = get_object_or_404(Post, id=id)
    user = request.user

    if user in post.like_users.all():
        post.like_users.remove(user)
    else:
        post.like_users.add(user)


    return redirect('posts:index')

15_Facebook/facebook/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  {% if user.is_authenticated %}
    <p>{{user.username}}</p>
    <a href="{% url 'accounts:logout' %}">로그아웃</a>
    <a href="{% url 'posts:create' %}">글쓰기</a>
  {% else %}
  <a href="{% url 'accounts:signup' %}">회원가입</a>
  <a href="{% url 'accounts:login' %}">로그인</a>
  {% endif %}

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
</body>
</html>

15_Facebook/posts/templates/posts/form.html
{% extends 'base.html' %}
{% block body %}
  <form action="" method="POST">
    {% csrf_token %}
    {{forms}}
    <input type="submit">
  </form>
{% endblock %}

15_Facebook/posts/templates/posts/index.html
{% extends 'base.html' %}
{% block body %}
<h1>index</h1>
  {% for post in posts %}
    <p>{{post.user.username}}</p>
    <p>{{post.title}}</p>
    {% if user in post.like_users.all %}
      <a href="{% url 'posts:like' post.id %}">좋아요취소</a>
    {% else %}
      <a href="{% url 'posts:like' post.id %}">좋아요</a>
    {% endif %}
    <hr>
  {% endfor %}
{% endblock %}