11_Form/form/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', views.index),
]

11_Form/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/detail/', views.detail, name='detail'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),
    path('create-model-form/', views.create_model_form, name='create_model_form'),

    path('<int:id>/update-model-form', views.update_model_form, name='update_model_form'),
    path('<int:id>/comment/create',views.comment_create, name='comment_create'),

]

11_Form/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    title_en = models.CharField(max_length=100)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=100)
    watch_grade = models.CharField(max_length=100)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()

class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

    class Meta:
        ordering = ('-id',)

11_Form/movies/forms.py
from django import forms
from .models import Movie, Comment

class MovieForm(forms.Form):
    title = forms.CharField(max_length=100)
    title_en = forms.CharField(
        max_length=100,
        label='영문제목',
        widget=forms.TextInput(
            attrs={
                'placeholder': '영문제목을 입력하세요',
                'class':'test_asdf'
            }
        )
    )
    audience = forms.IntegerField()
    open_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    genre = forms.CharField(max_length=100)
    watch_grade = forms.CharField(max_length=100)
    score = forms.FloatField()
    poster_url = forms.CharField(widget=forms.Textarea)
    description = forms.CharField(widget=forms.Textarea)

class MovieModelForm(forms.ModelForm):
    open_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    class Meta:
        model = Movie
        fields = '__all__'

class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

11_Form/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import MovieForm, MovieModelForm, CommentModelForm
from IPython import embed
from .models import Movie

# Create your views here.

def index(request):
    movies = Movie.objects.all().order_by('-id')
    context = {
        'movies':movies
    }

    return render(request, 'index.html', context)

def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        # request.POST 정상데이터

        if form.is_valid():
            movie = Movie()
            movie.title = form.cleaned_data.get('title')
            movie.title_en = form.cleaned_data.get('title_en')
            movie.audience = form.cleaned_data.get('audience')
            movie.open_date = form.cleaned_data.get('open_date')
            movie.genre = form.cleaned_data.get('genre')
            movie.watch_grade = form.cleaned_data.get('watch_grade')
            movie.score = form.cleaned_data.get('score')
            movie.poster_url = form.cleaned_data.get('poster_url')
            movie.description = form.cleaned_data.get('description')
            movie.save()

            return redirect('movies:index')

    else:
        form = MovieForm()

    # POST로 비정상적인 데이터검정에 실패한 폼
    # 기존의 정보가 담겨진 상태로 보여줌
    context = {
        'form':form
    }
    return render(request, 'form.html', context)

def detail(request, id):
    # movie = Movie.objects.get(id=id)

    movie = get_object_or_404(Movie, id=id)
    comment_form = CommentModelForm()
    context = {
        'movie':movie,
        'comment_form':comment_form
    }
    
    return render(request, 'detail.html', context)

def delete(request, id):
    if request.method == 'POST':
        # 기본인 GET요청으로 들어오면 삭제 안함
        movie = get_object_or_404(Movie, id=id)
        movie.delete()
        return redirect('movies:index')
    else:
        return redirect('movies:detail', id)

def update(request, id):
    movie = get_object_or_404(Movie, id=id)

    if request.method == 'POST':
        form = MovieForm(request.POST)
        
        if form.is_valid():
            movie.title = form.cleaned_data.get('title')
            movie.title_en = form.cleaned_data.get('title_en')
            movie.audience = form.cleaned_data.get('audience')
            movie.open_date = form.cleaned_data.get('open_date')
            movie.genre = form.cleaned_data.get('genre')
            movie.watch_grade = form.cleaned_data.get('watch_grade')
            movie.score = form.cleaned_data.get('score')
            movie.poster_url = form.cleaned_data.get('poster_url')
            movie.description = form.cleaned_data.get('description')
            movie.save()

            return redirect('movies:detail', id)

    else:
        form = MovieForm(initial=movie.__dict__)        
    
    context = {
        'form': form
    }
    return render(request, 'form.html', context)

def create_model_form(request):
    if request.method == 'POST':
        form = MovieModelForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.id)

    else:
        form = MovieModelForm()
    
    context = {
        'form':form
    }
    return render(request, 'form.html', context)

def update_model_form(request, id):
    movie = get_object_or_404(Movie, id=id)
    if request.method == 'POST':
        form = MovieModelForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', id)

    else:
        form = MovieModelForm(instance=movie)

    context = {
        'form':form
    }
    return render(request, 'form.html',context)

def comment_create(request, id):
    movie = get_object_or_404(Movie, id=id)
    if request.method == 'POST':
        form = CommentModelForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.movie = movie
            comment.save()
            return redirect('movies:detail', id)
    
    else:
        form = CommentModelForm(instance=comment)
    
    context = {
        'form':form
    }
    return redirect('movies:detail', id)

11_Form/movies/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  {% bootstrap_css %}
</head>
<body>
  <a href="{% url 'movies:index' %}">홈으로</a>
  <a href="{% url 'movies:create' %}">글쓰기</a>
  <a href="{% url 'movies:create_model_form' %}">글쓰기(모델폼)</a>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
</body>
</html>

11_Form/movies/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<h1>detail</h1>
<h3>{{movie.title}}</h3>
<h3>{{movie.open_date}}</h3>
{% comment %}
<a href="{% url 'movies:delete' movie.id %}">삭제</a>
{% endcomment %}
<form action="{% url 'movies:delete' movie.id %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="삭제">
</form>
<a href="{% url 'movies:update' movie.id %}">수정</a>
<a href="{% url 'movies:update_model_form' movie.id %}">수정(폼)</a>


<h1>댓글</h1>
<form action="{% url 'movies:comment_create' movie.id %}" method="POST">
  {% csrf_token %}  
  {{comment_form.as_p}}
  <input type="submit">
</form>
{% for comment in movie.comment_set.all %}
  <p>{{comment.content}}</p>
{% endfor %}
{% endblock %}

11_Form/movies/templates/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

  {% if request.resolver_match.url_name == "create_model_form" %}
    <h1>create</h1>
  {% else %}
    <h1>update</h1>
  {% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    {% bootstrap_form form %}
    {% buttons submit="제출" %}{% endbuttons %}
  </form>

{% endblock %}

11_Form/movies/templates/index.html
{% extends 'base.html' %}
{% block body %}
<h1>index</h1>
{% for movie in movies %}
<a href="{% url 'movies:detail' movie.id %}">{{movie.title}}:{{movie.title_en}}</a>
<br>

{% endfor %}
{% endblock %}