10_Either/questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),

    path('<int:id>/detail/', views.detail, name='detail'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:choice_id>/<int:select>/count/', views.count, name='count'),
    path('<int:question_id>/answer', views.answer_create, name='answer_create'),
    path('<int:question_id>/answer/<int:answer_id>/delete', views.answer_delete, name='answer_delete'),
]

10_Either/questions/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    pick_1 = models.TextField()
    pick_2 = models.TextField()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    pick_1_count = models.IntegerField()
    pick_2_count = models.IntegerField()

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField()

10_Either/questions/views.py
from django.shortcuts import render, redirect
from .models import Question, Choice, Answer
import random
# Create your views here.

def index(request):
    questions = Question.objects.all()

    random_question = random.choice(questions)

    context = {
        'questions':questions,
        'random_question':random_question,
    }

    return render(request, 'index.html', context)

def create(request):
    if request.method == "POST":
        question = Question.objects.create(pick_1=request.POST.get('pick_1'), pick_2=request.POST.get('pick_2'))
        choice = Choice.objects.create(pick_1_count=0, pick_2_count=0, question=question)

        return redirect('questions:index')
    else:
        return render(request, 'create.html')

def detail(request, id):
    question = Question.objects.get(id=id)
    # choice = question.choice_set
    context = {
        'question':question,
        # 'choice':choice,
    }
    return render(request, 'detail.html',context)

def update(request, id):
    question = Question.objects.get(id=id)

    if request.method == 'POST':
        question.pick_1 = request.POST.get('pick_1')
        question.pick_2 = request.POST.get('pick_2')
        question.save()

        return redirect('questions:detail', question.id)

    else:
        context = {
            'question':question
        }
        
        return render(request, 'update.html', context)

def delete(request, id):
    question = Question.objects.get(id=id)
    question.delete()

    return redirect('questions:index')

def count(request, choice_id, select):
    choice = Choice.objects.get(id=choice_id)
    if select == 1:
        choice.pick_1_count += 1
    else:
        choice.pick_2_count += 1

    choice.save()    

    return redirect('questions:detail', choice.question.id)

def answer_create(request, question_id):
    Answer.objects.create(answer=request.POST.get('answer'), question=Question.objects.get(id=question_id))

    return redirect('questions:detail', question_id)

def answer_delete(request, question_id, answer_id):
    answer = Answer.objects.get(id=answer_id)
    answer.delete()

    return redirect('questions:detail', question_id)

10_Either/questions/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>O.R</title>
  <link rel="icon" href="{% static 'or.png' %}">
  <script src="https://kit.fontawesome.com/dea07b509b.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body style="background: url('/static/bg.png')">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/questions/">O.R</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="/questions/create/">질문등록 <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="질문검색">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  <div class="container mt-5">
    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

10_Either/questions/templates/create.html
{% extends 'base.html' %}
{% block body %}
<h1 class="text-center">질문을 등록해 주세요</h1>
<div style="background-image: url('/static/create.png'); width: 100%; height: 410px; background-size: cover; background-position: center;">
  <form action="" method="POST" style="width: 100%; height: 100%">
    {% csrf_token %}
    <input class="rounded-pill border-danger text-center" style="position: relative; top:41%; left:11%; height:45px;" type="text" name="pick_1" placeholder="답변1">
    <input class="rounded-pill border-danger text-center" style="position: relative; top:41%; left:60%; height:45px;" type="text"  name="pick_2" placeholder="답변2">
    <span class="" style="position:relative; left:9%; top:103%">
      <input class="btn btn-primary col-2" type="submit" value="등록">
    </span>
  </form>
</div>
{% endblock %}

10_Either/questions/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div style="height: 100px;"></div>
{% for choice in question.choice_set.all %}
  {% if choice.pick_1_count == choice.pick_2_count %}
  <div style="background-image: url('/static/create.png'); width: 100%; height: 410px; background-size: cover; background-position: center;">
    <div class="card" style="width: 18rem; position: relative; left:5%; top:20%;">
      <div class="card-body bg-secondary">
        <h5 class="card-title" style="font-size: 3em; text-align:center;">
          <a href="{% url 'questions:count' choice.id 1 %}">{{question.pick_1}}</a>
        </h5>
        <p class="card-text" style="font-size: 3em; text-align:center;">{{question.choice_set.all.0.pick_1_count}}</p>
      </div>
    </div>
    <div class="card" style="width: 18rem; position: relative; left: 70%; bottom:34%;">
      <div class="card-body bg-secondary">
        <h5 class="card-title" style="font-size: 3em; text-align:center;"><a href="{% url 'questions:count' choice.id 2 %}">{{question.pick_2}}</a></h5>
        <p class="card-text" style="font-size: 3em; text-align:center;">{{question.choice_set.all.0.pick_2_count}}</p>
      </div>
    </div>    
  </div>
  {% elif choice.pick_1_count > choice.pick_2_count %}
  <div style="background-image: url('/static/left.png'); width: 100%; height: 600px; background-size: cover; background-position: center;">
    <div class="card" style="width: 18rem; position: relative; left:5%; top:40%;">
      <div class="card-body bg-secondary">
        <h5 class="card-title" style="font-size: 3em; text-align:center;"><a href="{% url 'questions:count' choice.id 1 %}">{{question.pick_1}}</a></h5>
        <p class="card-text" style="font-size: 3em; text-align:center;">{{question.choice_set.all.0.pick_1_count}}</p>
      </div>
    </div>
      <div class="card" style="width: 18rem; position: relative; left: 70%; bottom:20%;">
        <div class="card-body bg-secondary">
          <h5 class="card-title" style="font-size: 3em; text-align:center;"><a href="{% url 'questions:count' choice.id 2 %}">{{question.pick_2}}</a></h5>
          <p class="card-text" style="font-size: 3em; text-align:center;">{{question.choice_set.all.0.pick_2_count}}</p>
        </div>
      </div>
  </div>
  {% else %}
  <div style="background-image: url('/static/right.png'); width: 100%; height: 600px; background-size: cover; background-position: center;">
      <div class="card" style="width: 18rem; position: relative; left:5%; top:20%;">
        <div class="card-body bg-secondary">
          <h5 class="card-title" style="font-size: 3em; text-align:center;"><a href="{% url 'questions:count' choice.id 1 %}">{{question.pick_1}}</a></h5>
          <p class="card-text" style="font-size: 3em; text-align:center;">{{question.choice_set.all.0.pick_1_count}}</p>
        </div>
      </div>

    
      <div class="card" style="width: 18rem; position: relative; left: 70%; bottom:0%;">
        <div class="card-body bg-secondary">
          <h5 class="card-title" style="font-size: 3em; text-align:center;"><a href="{% url 'questions:count' choice.id 2 %}">{{question.pick_2}}</a></h5>
          <p class="card-text" style="font-size: 3em; text-align:center;">{{question.choice_set.all.0.pick_2_count}}</p>
        </div>
      </div>
  </div>
  {% endif %}
{% endfor %}


<a class="btn btn-danger col-2" href="{% url 'questions:update' question.id %}">변경</a>
<a class="btn btn-success col-2" href="{% url 'questions:delete' question.id %}">삭제</a>

{% if question.answer_set.all %}
  {% for answer in question.answer_set.all %}
    <h5>{{answer.answer}}
      <a href="{% url 'questions:answer_delete' question.id answer.id %}" class="btn btn-danger">삭제</a>
    </h5>
  {% endfor %}

{% else %}
  <div>댓글이 없습니다.</div>

{% endif %}

<form action="{% url 'questions:answer_create' question.id %}" method="POST">
  {% csrf_token %}
  <input type="text" name="answer">
  <input type="submit">
</form>
{% endblock %}

10_Either/questions/templates/index.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<br>
<br>
<br>
<a href="{% url 'questions:detail' random_question.id %}" style="position: relative; left:40%; top:20%;"><img src="{% static 'RANDOM.png' %}" alt=""></a>
<br>
<br>
<br>
<div class="bd-example border boder-warnng rounded rounded-lg">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      {% for question in questions %}
        <li data-target="#carouselExampleCaptions" data-slide-to="{{ forloop.counter }}" class="active"></li>
      {% endfor %}
    </ol>
    
    <div class="carousel-inner">      
      <img src="{% static 'create.png' %}" class="d-block w-100" alt="...">
      {% for question in questions %}
        {% if forloop.counter == 1 %}
        <div class="carousel-item active">          
            <div class="carousel-caption d-none d-md-block" style="bottom: 30%; right: 5%; left: 5%;">
              <div class="d-flex justify-content-between">
                <div class="card" style="width: 18rem;">
                  <div class="card-body bg-secondary">
                    <h5 class="card-title" style="font-size: 3em;">{{question.pick_1}}</h5>
                    <p class="card-text">{{question.choice_set.all.0.pick_1_count}}</p>
                  </div>
                </div>
                <div class="card" style="width: 18rem;">
                  <div class="card-body bg-secondary">
                    <h5 class="card-title" style="font-size: 3em;">{{question.pick_2}}</h5>
                    <p class="card-text">{{question.choice_set.all.0.pick_2_count}}</p>
                  </div>
                </div>
            </div>
            <h1 class="mt-5 text-primary" ><a href="{% url 'questions:detail' question.id %}">클릭! 지금 바로 투표하세요!</a></h1>
            </div>
          </div>
        {% else %}
        <div class="carousel-item">          
            <div class="carousel-caption d-none d-md-block" style="bottom: 30%; right: 5%; left: 5%;">
              <div class="d-flex justify-content-between">
                <div class="card" style="width: 18rem;">
                  <div class="card-body bg-secondary">
                    <h5 class="card-title" style="font-size: 3em;">{{question.pick_1}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                    <p class="card-text">{{question.choice_set.all.0.pick_1_count}}</p>
                  </div>
                </div>
                <div class="card" style="width: 18rem;">
                  <div class="card-body bg-secondary">
                    <h5 class="card-title" style="font-size: 3em;">{{question.pick_2}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                    <p class="card-text">{{question.choice_set.all.0.pick_2_count}}</p>
                  </div>
                </div>
            </div>
            <h1 class="mt-5 text-primary" ><a href="{% url 'questions:detail' question.id %}">클릭! 지금 바로 투표하세요!</a></h1>
           </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
    <a class="carousel-control-prev bg-info" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="false"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next bg-info" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="false"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<h1 style="text-align: center; margin-top:40px; font-size:5rem;">와우! 너무 즐겁다!</h1>
<h2 style="text-align: center; color:red">Use Full screen to full experience</h1>
{% endblock %}

10_Either/questions/templates/update.html
{% extends 'base.html' %}
{% block body %}
<h1 class="text-center">질문을 수정해 주세요</h1>
<div style="background-image: url('/static/create.png'); width: 100%; height: 410px; background-size: cover; background-position: center;">
  <form action="" method="POST" style="width: 100%; height: 100%">
    {% csrf_token %}
    <input class="rounded-pill border-danger text-center" style="position: relative; top:41%; left:11%" type="text" name="pick_1" value="{{question.pick_1}}">
    <input class="rounded-pill border-danger text-center" style="position: relative; top:41%; left:60%" type="text"  name="pick_2" value="{{question.pick_2}}">
    <span class="" style="position:relative; left:9%; top:103%">
      <input class="btn btn-primary col-2" type="submit" value="수정">
    </span>
  </form>
</div>
{% endblock %}